#!/usr/bin/env ruby

require "thor"

class Pier < Thor
  desc "install GITHUB_REPO", "install GITHUB_REPO"
  def install(repo)
    namespaced_repo = repo.sub('/', '.')

    codebase_dir = "/codebase"
    repo_dir = "#{codebase_dir}/#{namespaced_repo}"

    if !Dir.exist?(repo_dir) then
      git_output = %x(
        cd "#{codebase_dir}" \
          && git clone git@github.com:#{repo}.git "#{repo_dir}" 2>&1
      )

      if $?.exitstatus != 0 then
        STDERR.puts "Error while cloning #{repo}:\n#{git_output}"
      end
    end

    if File.exist?("#{repo_dir}/configure") then
      configure_output = %x(
        cd "#{repo_dir}" \
          && ./configure docker
      )

      if $?.exitstatus != 0 then
        STDERR.puts "Error while running \`./configure docker\`:\n#{configure_output}"
      end
    end

    if File.exist?("#{repo_dir}/make") then
      configure_output = %x(
        cd "#{repo_dir}" \
          && make install
      )

      if $?.exitstatus != 0 then
        STDERR.puts "Error while running \`make install\`:\n#{configure_output}"
      end
    end
  end
end

Pier.start(ARGV)
